language: generic

jdk:
  - openjdk6
  - oraclejdk6
  - openjdk7
  - oraclejdk7
  - openjdk8
  - oraclejdk8


cache:
  directories:
    - "$HOME/.m2/repository"

script:
  - mvn -v
  - mvn clean cobertura:cobertura -Dmaven.test.skip=false -Pgithub-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)