language: generic

jdk:
  - openjdk6
  - oraclejdk6

cache:
  directories:
    - "$HOME/.m2/repository"

script:
  - cd bin
  - ./sandbox-packages.sh
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)